import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "./globals.css";

const PTSans = PT_Sans({
  subsets: ['cyrillic'],
  variable: '--font-PT_Sans',
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PTSans.variable} antialiased`}
      >
        <main  className="min-h-screen">
            {children}
          </main>
      </body>
    </html>
  );
}
